FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["BudgetBot/BudgetBot.csproj", "BudgetBot/"]
RUN dotnet restore "BudgetBot/BudgetBot.csproj"
COPY . .
WORKDIR "/src/BudgetBot"
RUN dotnet build "BudgetBot.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BudgetBot.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BudgetBot.dll"]
